### ISSUE TITLE
输出计数结果部分代码在哪里

### ISSUE THREAD

**Issue by vidiy** [owo12321/Yolov5_DeepSort_Traffic-counter#4]
你好，请问一下您这个项目最后输出的计数结果的代码是哪一部分啊？

**Comment by owo12321** [comment]
count.py第394行的total_num

**Comment by vidiy** [comment]
非常感谢，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "owo12321/Yolov5_DeepSort_Traffic-counter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 晚上11:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [owo12321/Yolov5_DeepSort_Traffic-counter] 输出计数结果部分代码在哪里 (Issue #4)





 
count.py第394行的total_num
